apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: ""
    - name: image
      type: string
    - name: context
      type: string
      default: .
    - name: dockerfile
      type: string
      default: ./Dockerfile
  workspaces:
    - name: source
    - name: git-auth
      optional: true
    - name: image-auth
      optional: true
  tasks:
    - name: checkout
      taskRef:
        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/kudeploy/kudeploy-manifests/main/tekton/tasks/git-clone.yaml
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: git-auth
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: depth
          value: "1"
        - name: deleteExisting
          value: "true"
    - name: build-and-push
      runAfter:
        - checkout
      taskRef:
        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/kudeploy/kudeploy-manifests/main/tekton/tasks/buildah.yaml
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: image-auth
      params:
        - name: IMAGE
          value: $(params.image)
        - name: CONTEXT
          value: $(params.context)
        - name: DOCKERFILE
          value: $(params.dockerfile)
