apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image
      type: string
  workspaces:
    - name: source
    - name: git-auth
      optional: true
    - name: image-auth
      optional: true
  tasks:
    - name: checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: dd7cc22f2965ff4c9d8855b7161c2ffe94b6153e
          - name: pathInRepo
            value: task/git-clone/0.10/git-clone.yaml
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: git-auth
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: depth
          value: "1"
        - name: deleteExisting
          value: "true"
    - name: build-and-push
      runAfter:
        - checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: cbc42eb541d822bd7b3fad85b5bb76727152eb9e
          - name: pathInRepo
            value: task/buildah/0.9/buildah.yaml
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: image-auth
      params:
        - name: IMAGE
          value: $(params.image)
